import Foundation
import PackagePlugin

@main
struct SwiftLintPlugin: BuildToolPlugin {
    func createBuildCommands(context: PluginContext, target: Target) async throws -> [Command] {
        let swiftlintExecutable = try context.tool(named: "swiftlint")

        guard let sourceTarget = target as? SourceModuleTarget else {
            return []
        }

        let swiftFiles = sourceTarget.sourceFiles(withSuffix: "swift").map(\.url)
        guard !swiftFiles.isEmpty else {
            return []
        }

        // パッケージディレクトリから上に向かって .swiftlint.yml が存在するディレクトリを探す
        let workingDirectory = findConfigDirectory(startingFrom: context.package.directoryURL)

        return try makeBuildCommands(
            targetName: target.name,
            swiftFiles: swiftFiles,
            workingDirectory: workingDirectory,
            pluginWorkDirectoryURL: context.pluginWorkDirectoryURL,
            swiftlintExecutable: swiftlintExecutable
        )
    }

    /// .swiftlint.yml が存在するディレクトリを見つける（パッケージディレクトリから上の階層に向かって探す）
    func findConfigDirectory(startingFrom directoryURL: URL) -> URL {
        var current = directoryURL.standardized
        while current.pathComponents.count > 1 {
            if FileManager.default.fileExists(atPath: current.appending(path: ".swiftlint.yml").path(percentEncoded: false)) {
                return current
            }
            current = current.deletingLastPathComponent()
        }
        return directoryURL
    }

    func makeBuildCommands(
        targetName: String,
        swiftFiles: [URL],
        workingDirectory: URL,
        pluginWorkDirectoryURL: URL,
        swiftlintExecutable: PluginContext.Tool
    ) throws -> [Command] {
        let cacheURL = pluginWorkDirectoryURL.appending(path: "Cache")
        try FileManager.default.createDirectory(at: cacheURL, withIntermediateDirectories: true)
        // lintが通った印。prebuildCommandは変更がなくても毎ビルド全ターゲットを直列に走らせるため、
        // 入出力を宣言できるbuildCommandにして、入力が変わったターゲットだけを並列にlintさせる。
        // buildCommandはビルドが出力を使うときしか走らないので、ターゲットにコンパイルされる空のSwiftファイルを出力にする
        let stampURL = pluginWorkDirectoryURL.appending(path: "\(targetName)+SwiftLintStamp.swift")
        let configURL = workingDirectory.appending(path: ".swiftlint.yml")

        // lintが失敗したら印を更新しないので、次のビルドでもlintが走りエラーが出続ける
        let script = """
        linter="$1"; cache="$2"; stamp="$3"; shift 3
        "$linter" lint --quiet --force-exclude --cache-path "$cache" "$@" && echo "// Generated by SwiftLintPlugin" > "$stamp"
        """
        let arguments: [String] = [
            "-c", script, "swiftlint-plugin",
            swiftlintExecutable.url.path(percentEncoded: false),
            cacheURL.path(percentEncoded: false),
            stampURL.path(percentEncoded: false),
        ] + swiftFiles.map { $0.path(percentEncoded: false) }

        var inputFiles = swiftFiles + [swiftlintExecutable.url]
        if FileManager.default.fileExists(atPath: configURL.path(percentEncoded: false)) {
            inputFiles.append(configURL)
        }

        return [
            .buildCommand(
                displayName: "SwiftLint \(targetName)",
                executable: URL(filePath: "/bin/sh"),
                arguments: arguments,
                environment: ["BUILD_WORKSPACE_DIRECTORY": workingDirectory.path(percentEncoded: false)],
                inputFiles: inputFiles,
                outputFiles: [stampURL]
            ),
        ]
    }
}

#if canImport(XcodeProjectPlugin)
import XcodeProjectPlugin

extension SwiftLintPlugin: XcodeBuildToolPlugin {
    func createBuildCommands(context: XcodePluginContext, target: XcodeTarget) throws -> [Command] {
        let swiftlintExecutable = try context.tool(named: "swiftlint")

        let swiftFiles = target.inputFiles.filter { $0.url.pathExtension == "swift" }.map(\.url)
        guard !swiftFiles.isEmpty else {
            return []
        }

        let workingDirectory = findConfigDirectory(startingFrom: context.xcodeProject.directoryURL)

        return try makeBuildCommands(
            targetName: target.displayName,
            swiftFiles: swiftFiles,
            workingDirectory: workingDirectory,
            pluginWorkDirectoryURL: context.pluginWorkDirectoryURL,
            swiftlintExecutable: swiftlintExecutable
        )
    }
}
#endif
