# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  before_all do
    setup_ci if ENV['CI']
  end

  desc "ipaを生成"
  lane :make_ipa do |options|
    xcargs = "-allowProvisioningUpdates -authenticationKeyIssuerID #{ENV['ASC_ISSUER_ID']} -authenticationKeyID #{ENV['ASC_KEY_ID']} -authenticationKeyPath #{ENV['ASC_API_KEY_PATH']}"
    gym(
      project: "homete.xcodeproj",
      scheme: "homete",
      output_directory: "Build/app",
      cloned_source_packages_path: "SourcePackages",
      export_method: "app-store",
      export_options: options[:export_options_path],
      xcargs: xcargs
    )
  end

  desc "指定されたipaでTestFlight配信を行う"
  lane :upload_testFlight do |options|
    # ipa生成
    make_ipa(options)

    # ipaをTestFlight用にアップロード
    api_key = generate_api_key(options)
    upload_to_testflight(
      ipa: "Build/app/homete.ipa",
      api_key: api_key
    )
  end

  desc "指定されたipaでApp Storeリリースを行う"
  lane :release do |options|
    api_key = generate_api_key(options)
    ipa_path = options[:ipa]

    upload_to_app_store(
      ipa: ipa_path,
      api_key: api_key
    )

    app_version = options[:app_version]

    add_git_tag(
      tag: "v#{app_version}",
      force: true
    )

    push_git_tags(
      force: true,
      tag: "v#{app_version}"
    )
  end

  private_lane :generate_api_key do |options|
    app_store_connect_api_key(
      key_id: ENV['ASC_KEY_ID'],
      issuer_id: ENV['ASC_ISSUER_ID'],
      key_filepath: ENV['ASC_API_KEY_PATH'],
      in_house: false
    )
  end
end
