# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "指定されたipaでTestFlight配信を行う"
  lane :upload_testFlight do |options|
    api_key = generate_api_key(options)
    ipa_path = options[:ipa]

    upload_to_testflight(
      ipa: ipa_path,
      api_key: api_key
    )
  end

  desc "指定されたipaでApp Storeリリースを行う"
  lane :release do |options|
    api_key = generate_api_key(options)
    ipa_path = options[:ipa]

    upload_to_app_store(
      ipa: ipa_path,
      api_key: api_key
    )
  end

  private_lane :generate_api_key do |options|
    app_store_connect_api_key(
      key_id: options[:asc_key_id],
      issuer_id: options[:asc_issuer_id],
      key_filepath: options[:asc_key_path],
      in_house: false
    )
  end
end
