# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: deploy_test_flight

on:
  workflow_call:

env:
  # チェックアウト
  DEVELOPER_DIR: /Applications/Xcode_26.0.app
  WORKSPACE_DIR: homete.xcodeproj
  BUILD_SCHEME: homete
  TEST_FLIGHT_EXPORT_OPTION_PATH: deploy/config/ExportOptions_TestFlight.plist
  ARCHIVE_PATH: Build/homete.xcarchive
  EXPORT_PATH: Build/app
  SPM_CLONE_PATH: SourcePackages
  SPM_PACKAGE_RESOLVED_FILE_PATH: homete.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

jobs:
  deploy_testFlight:
    # 実行環境はmacosに設定
    runs-on: macos-26
    env:
      API_KEY_PATH: "private_keys/AuthKey_${{ secrets.ASC_KEY_ID }}.p8"

    steps:
      # fetch-depth の計算
      - run: echo "fetch_depth=$(( commits + 1 ))" >> $GITHUB_ENV
        env:
          commits: ${{ github.event.pull_request.commits }}

      # チェックアウト(リポジトリからソースコードを取得)
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: ${{ env.fetch_depth }}

      # Xcodeの一覧出力
      - name: Show Xcode list
        run: ls /Applications | grep 'Xcode'

      # Xcodeのバージョン選択
      - name: Select Xcode version
        run: sudo xcode-select -s '${{ env.DEVELOPER_DIR }}/Contents/Developer'

      # Xcodeのバージョン出力
      - name: Show Xcode version
        run: xcodebuild -version

      # iOS SDKのインストール
      - name: Install ios sdk
        run: xcodebuild -downloadPlatform iOS

      # ASC_API_KEYのファイルを生成
      - name: Setup api key
        run: scripts/create_api_key_file.sh "$API_KEY_PATH" private_keys "${{ secrets.ASC_SECRET_KEY }}"

      # ASC_API_KEYの絶対パスを環境変数へ設定
      - name: Setup env for api key path
        run: echo "API_KEY_ABSOLUTE_PATH=$(pwd)/$API_KEY_PATH" >> $GITHUB_ENV

      # Gemfileの依存ライブラリキャッシュ
      - name: cache bundle directory
        uses: actions/cache@v4.2.2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-${{ hashFiles('Gemfile.lock') }}

      # Gemfileの依存ライブラリインストール
      - name: Install Gemfile lib
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      # SPMのライブラリのキャッシュ
      - name: Cache Swift Packages
        uses: actions/cache@v4.2.2
        with:
          path: ${{ env.SPM_CLONE_PATH }}
          key: ${{ runner.os }}-spm-${{ hashFiles(env.SPM_PACKAGE_RESOLVED_FILE_PATH) }}
          restore-keys: ${{ runner.os }}-spm-

      - name: Decode Firebase Api Key
        run: echo "${{ secrets.FIREBASE_API_KEY_BASE64 }}" | base64 --decode > homete/GoogleService-Info.plist

      # ビルド番号更新
      - name: Increment build number
        run: xcrun agvtool new-version -all ${{ github.run_number }}

      # IPAをApp Store Connectへアップロードする
      - name: Upload ipa for TestFlight
        run: fastlane upload_testFlight
        env:
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_API_KEY_PATH: ${{ env.API_KEY_ABSOLUTE_PATH }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GITHUB_TOKEN }}

      # ipaをワークフローのアーティファクトとしてアップロード
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: Build/
