# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: build_test

on:
  push:
    branches:
      - "main"
      - "release/*"
  pull_request:
    branches:
      - "**"
    paths-ignore:
      - ".github/ISSUE_TEMPLATE/*"
      - ".gitignore"
      - README.md
  workflow_dispatch:

env:
  # チェックアウト
  DEVELOPER_DIR: /Applications/Xcode_16.2.app
  WORKSPACE_DIR: homete.xcodeproj
  BUILD_SCHEME: homete
  TEST_PLAN: homete
  SPM_CLONE_PATH: SourcePackages
  SPM_PACKAGE_RESOLVED_FILE_PATH: homete.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

jobs:
  build:
    # 実行環境はmacosに設定
    runs-on: macos-latest

    steps:
      # fetch-depth の計算
      - run: echo "fetch_depth=$(( commits + 1 ))" >> $GITHUB_ENV
        env:
          commits: ${{ github.event.pull_request.commits }}

      # チェックアウト(リポジトリからソースコードを取得)
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: ${{ env.fetch_depth }}

      # Xcodeの一覧出力
      - name: Show Xcode list
        run: ls /Applications | grep 'Xcode'

      # Xcodeのバージョン選択
      - name: Select Xcode version
        run: sudo xcode-select -s '${{ env.DEVELOPER_DIR }}/Contents/Developer'

      # Xcodeのバージョン出力
      - name: Show Xcode version
        run: xcodebuild -version

      # SPMのライブラリのキャッシュ
      - name: Cache Swift Packages
        uses: actions/cache@v4.2.2
        with:
          path: SourcePackages
          key: v1-dev-${{ runner.os }}-spm-${{ hashFiles(env.SPM_PACKAGE_RESOLVED_FILE_PATH) }}
          restore-keys: v1-dev-${{ runner.os }}-spm-

      - name: Decode Firebase Api Key
        run: echo "${{ secrets.DEV_FIREBASE_API_KEY_BASE64 }}" | base64 --decode > homete/GoogleService-Info-dev.plist

      - name: Xcode Resolve Package Dependencies
        run: set -o pipefail &&
          xcodebuild
          -project "${WORKSPACE_DIR}"
          -scheme "${BUILD_SCHEME}"
          -configuration Debug
          -clonedSourcePackagesDirPath "${SPM_CLONE_PATH}"
          -skipPackagePluginValidation
          -skipMacroValidation
          -scmProvider xcode
          -resolvePackageDependencies

      # 単体テストの実行
      - name: Xcode test
        run: set -o pipefail &&
          xcodebuild
          -project "${WORKSPACE_DIR}"
          -configuration Debug
          -destination 'platform=iOS Simulator,OS=18.1,name=iPhone 16 Pro'
          -scheme "${BUILD_SCHEME}"
          -testPlan "${TEST_PLAN}"
          -skipPackagePluginValidation
          -skipMacroValidation
          -scmProvider xcode
          -clonedSourcePackagesDirPath "${SPM_CLONE_PATH}"
          clean test |
          xcbeautify --renderer github-actions

  # Deploy(TestFlight)
  call_deploy:
    if: github.ref_name == 'main'
    needs: build
    uses: ./.github/workflows/cd_testFlight.yml
    secrets: inherit

  # Deploy(Release)
  call_deploy_release:
    if: github.ref_name == 'release/*'
    needs: build
    uses: ./.github/workflows/cd_release.yml
    secrets: inherit
