# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: update_snapshot_images

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - ".github/ISSUE_TEMPLATE/*"
      - ".gitignore"
      - README.md
  workflow_dispatch:

env:
  # チェックアウト
  DEVELOPER_DIR: /Applications/Xcode_26.0.app
  WORKSPACE_DIR: homete.xcodeproj
  BUILD_SCHEME: homete
  TEST_PLAN: homete-snapshot-testing
  SPM_CLONE_PATH: SourcePackages
  SPM_PACKAGE_RESOLVED_FILE_PATH: homete.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  PROJECT_TOOLS_SPM_PACKAGE_RESOLVED_FILE_PATH: ProjectTools/Package.resolved
  TEST_OUTPUT_PATH: Build/test.xcresult

jobs:
  build:
    # 実行環境はmacosに設定
    runs-on: macos-26

    steps:
      # チェックアウト(リポジトリからソースコードを取得)
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Get latest commit of default branch
        id: get_commit
        run: |
          DEFAULT_BRANCH=${{ github.event.repository.default_branch }}
          git fetch origin $DEFAULT_BRANCH
          LATEST_COMMIT=$(git rev-parse origin/$DEFAULT_BRANCH)
          echo "LATEST_COMMIT=$LATEST_COMMIT"
          echo "commit_sha=$LATEST_COMMIT" >> $GITHUB_OUTPUT

      # Xcodeの一覧出力
      - name: Show Xcode list
        run: ls /Applications | grep 'Xcode'

      # Xcodeのバージョン選択
      - name: Select Xcode version
        run: sudo xcode-select -s '${{ env.DEVELOPER_DIR }}/Contents/Developer'

      # Xcodeのバージョン出力
      - name: Show Xcode version
        run: xcodebuild -version

      # SPMのライブラリのキャッシュ
      - name: Cache Swift Packages For Project
        uses: actions/cache@v4.2.2
        with:
          path: SourcePackages
          key: v1-dev-${{ runner.os }}-spm-${{ hashFiles(env.SPM_PACKAGE_RESOLVED_FILE_PATH) }}
          restore-keys: v1-dev-${{ runner.os }}-spm-

      - name: Xcode Resolve Package Dependencies
        run: set -o pipefail &&
          xcodebuild
          -project "${WORKSPACE_DIR}"
          -scheme "${BUILD_SCHEME}"
          -configuration Debug
          -clonedSourcePackagesDirPath "${SPM_CLONE_PATH}"
          -skipPackagePluginValidation
          -skipMacroValidation
          -scmProvider xcode
          -resolvePackageDependencies

      # Snapshotの生成
      - name: Generate snapshot
        run: xcodebuild
          -project "${WORKSPACE_DIR}"
          -configuration Debug
          -destination 'platform=iOS Simulator,OS=18.6,name=iPhone 16 Pro'
          -scheme "${BUILD_SCHEME}"
          -testPlan "${TEST_PLAN}"
          -clonedSourcePackagesDirPath "${SPM_CLONE_PATH}"
          clean test |
          xcbeautify --renderer github-actions

      # Snapshotのキャッシュを保存
      - name: Cache snapshot
        uses: actions/cache/save@v4
        with:
          path: hometeSnapshotTests/__Snapshots__/
          key: v1-snapshot-images-${{ steps.get_commit.outputs.commit_sha }}
